name: templater
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_cli: ^1.8.4
  get: ^4.6.6
  image: ^4.3.0
  universal_html: ^2.2.4
  cloud_firestore: ^5.6.3
  firebase_core: ^3.10.1
  firebase_analytics: ^11.4.1
  translator: ^1.0.3+1
  archive: ^3.6.1
  flutter_colorpicker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  fonts:
    - family: Verdana
      fonts:
        - asset: assets/fonts/verdana/verdana.ttf
          style: normal
        - asset: assets/fonts/verdana/verdana-bold.ttf
          weight: 700
        - asset: assets/fonts/verdana/verdana-bold-italic.ttf
          style: italic
    - family: Timer New Roman
      fonts:
        - asset: assets/fonts/times_new_roman/times.ttf
          style: normal
    - family: Segeo UI This
      fonts:
        - asset: assets/fonts/segoe_ui_this/segoeuithis.ttf
          style: normal
    - family: Cambria
      fonts:
        - asset: assets/fonts/cambria/cambria_regular.ttf
          style: normal
    - family: Calibri
      fonts:
        - asset: assets/fonts/calibri/calibri.ttf
          style: normal
    - family: Arial
      fonts:
        - asset: assets/fonts/arial/arial.ttf
          style: normal



assets:
  - assets/background.png
