// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqjej1AAnLg3rS3x4WzP59Djjg_0yL5Hk',
    appId: '1:528730512583:web:67f8ff2ca8b51b7c9ff2e2',
    messagingSenderId: '528730512583',
    projectId: 'templater-3e947',
    authDomain: 'templater-3e947.firebaseapp.com',
    storageBucket: 'templater-3e947.firebasestorage.app',
    measurementId: 'G-DSXJMRSM07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJh_Eu1Bq22xOC5vj01GEVj22nNGmxbzY',
    appId: '1:528730512583:android:f08dcb76615a87619ff2e2',
    messagingSenderId: '528730512583',
    projectId: 'templater-3e947',
    storageBucket: 'templater-3e947.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr9Ni0kmKa-ZZTE3ojYkF0mSsBUMWR6ek',
    appId: '1:528730512583:ios:9f34c7390ee716f29ff2e2',
    messagingSenderId: '528730512583',
    projectId: 'templater-3e947',
    storageBucket: 'templater-3e947.firebasestorage.app',
    iosBundleId: 'com.templater.templater',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr9Ni0kmKa-ZZTE3ojYkF0mSsBUMWR6ek',
    appId: '1:528730512583:ios:9f34c7390ee716f29ff2e2',
    messagingSenderId: '528730512583',
    projectId: 'templater-3e947',
    storageBucket: 'templater-3e947.firebasestorage.app',
    iosBundleId: 'com.templater.templater',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMUs9P1pjb-O46cA7LWjmiMvZ-LRNd13k',
    appId: '1:528730512583:web:876f6288462778809ff2e2',
    messagingSenderId: '528730512583',
    projectId: 'templater-3e947',
    authDomain: 'templater-3e947.firebaseapp.com',
    storageBucket: 'templater-3e947.firebasestorage.app',
    measurementId: 'G-RMRTJ5703Z',
  );
}
